field: 670c03fe-0f4d-476f-b8df-f547c2b76da3 # Project Modules
fieldLayouts:
  9fa2a231-b1ee-438d-b371-edf5fcfdc308:
    tabs:
      -
        elements:
          -
            fieldUid: 60529cb1-5e81-4fc9-a15a-073698f15cbb # Project Info Section One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 276d970f-f7a5-4116-a87c-5a317afb3192 # Project Info Section Two
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  276d970f-f7a5-4116-a87c-5a317afb3192: # Project Info Section Two
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: projectInfoSectionTwo
    instructions: ''
    name: 'Project Info Section Two'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  60529cb1-5e81-4fc9-a15a-073698f15cbb: # Project Info Section One
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: projectInfoSectionOne
    instructions: ''
    name: 'Project Info Section One'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: projectInfo
name: 'Project Info'
sortOrder: 4
