field: 670c03fe-0f4d-476f-b8df-f547c2b76da3 # Project Modules
fieldLayouts:
  bda814e9-76fb-4329-b2d2-1f02a441b446:
    tabs:
      -
        elements:
          -
            fieldUid: 47466915-4a43-4556-aafd-f69d5675f48e # Single Image Landscape Inset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dc518f4c-dc65-4b41-a20b-bce28b9ed154 # Single Image Landscape Inset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  47466915-4a43-4556-aafd-f69d5675f48e: # Single Image Landscape Inset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: singleImageLandscapeInset
    instructions: ''
    name: 'Single Image Landscape Inset'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fe0527a7-52ff-443b-be56-4439575db75f' # Project
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fe0527a7-52ff-443b-be56-4439575db75f' # Project
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  dc518f4c-dc65-4b41-a20b-bce28b9ed154: # Single Image Landscape Inset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: singleImageLandscapeInsetMobile
    instructions: ''
    name: 'Single Image Landscape Inset'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fe0527a7-52ff-443b-be56-4439575db75f' # Project
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fe0527a7-52ff-443b-be56-4439575db75f' # Project
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: singleImageLandscapeInset
name: 'Single Image Landscape Inset'
sortOrder: 3
