columnSuffix: null
contentColumnType: string
fieldGroup: 16a17e30-30e0-4c2d-b6ee-f8fc93258003 # Home
handle: homepageProject
instructions: ''
name: 'Homepage Project'
searchable: false
settings:
  contentTable: '{{%matrixcontent_homepageproject}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
