dateModified: 1645133645
email:
  fromEmail: sam@sampittman.co.uk
  fromName: 'Sam Pittman'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0aa024b4-22b9-49a6-8b66-c73cf2996494: Home # Home
    0d0f5e90-ee72-4664-a913-5db06d807622: 'Project Info' # Project Info
    0ea2600b-91f3-4320-8cf6-2f3139b48551: 'Sam Pittman' # Sam Pittman
    0f3abd88-2a6d-4aea-bc4b-80cc53a7709e: 'Awards Project' # Awards Project
    1cf2fcf9-b20b-492c-b904-ffc6156f956a: 'Project Block' # Project Block
    1e50705b-7087-42d9-954f-f8d29a2b4c33: Contact # Contact
    2a2274e8-2cd0-43b4-9a44-92d22fbd651c: 'Video Webm' # Video Webm
    2b2ae9f3-3fea-4e03-b0b8-f0cd0e6301d7: Bio # Bio
    2bfe5e30-2fa9-471e-b31d-03217d61dd2a: 'Video Mp4' # Video Mp4
    2d88c141-a2d3-4f5e-8625-311ad5df7072: 'Iphone Images Mobile' # Iphone Images Mobile
    3a3acbb2-252b-43d3-b4de-1cf41d9048f9: 'Background colour' # Background colour
    3c6e1b63-e3af-4833-b1aa-cb7401b0e9a3: 'Awards Level' # Awards Level
    4e5f65a0-c3e0-4eee-9009-555998383c4b: 'Project Info Section One' # Project Info Section One
    5dd21671-2fb4-4698-b61b-b227c2ef93fc: 'Awards Organisation' # Awards Organisation
    5fb3e8dd-797e-40c6-924d-4f129ce91c8b: Contact # Contact
    6c193a40-338d-4152-8f5a-5513389045d3: 'Single Image Portrait Mobile' # Single Image Portrait Mobile
    6d329784-1794-4cab-bd61-1c90ed8f4168: 'Project Name' # Project Name
    08ef0892-3083-45d3-adcb-7a3738d45681: Default # Default
    9e386387-1a17-495a-a9ff-1759b7137041: 'Single Image Portrait Mobile' # Single Image Portrait Mobile
    009fc447-857b-4048-938f-11e4d0366602: 'Single Image Portrait' # Single Image Portrait
    16a17e30-30e0-4c2d-b6ee-f8fc93258003: Home # Home
    22cb4576-cf84-47e1-a467-a687efc7b5a7: 'Video Webm' # Video Webm
    29ec3893-5153-4121-a847-315080ca046c: 'Single Image Mobile' # Single Image Mobile
    31d2fd36-fc55-4818-9a78-6d620bf82d51: 'Project Image' # Project Image
    52b89fab-f906-4ab4-ac63-06b800deb68f: 'Autoplaying Video' # Autoplaying Video
    57c3927b-5dc1-4127-bfd1-6430d4678574: 'Homepage Main Project Name' # Homepage Main Project Name
    57e800b0-660f-41c7-a8f1-a9aa03d7abfc: 'Main Project Image Mobile' # Main Project Image Mobile
    66c7d54c-1e17-48e6-8b1b-abb119a045f6: 'Single Image Landscape Inset' # Single Image Landscape Inset
    88a98421-0921-4a2b-a106-ebc37a68e910: 'Awards Block' # Awards Block
    142bde7d-7f4b-4fe0-b72d-461969b00785: Carousel # Carousel
    183c7dba-e04b-45cc-a730-bd1056ab50f8: 'Player Video' # Player Video
    239bbaa5-f307-4c21-8eb9-ba661aae8f5e: 'Project Type' # Project Type
    276d970f-f7a5-4116-a87c-5a317afb3192: 'Project Info Section Two' # Project Info Section Two
    670c03fe-0f4d-476f-b8df-f547c2b76da3: 'Project Modules' # Project Modules
    753f672f-8bfe-4b76-9d83-fc321001e250: 'Project Info Section One' # Project Info Section One
    0832a5dc-1a83-4c36-a295-8b5da78d2bc5: Contact # Contact
    995b66b9-435e-4a56-9c97-c2ff1284cf6f: 'Project Name' # Project Name
    4661d1b3-3bc6-42e6-9401-b57d9e57ee78: 'Video Mp4' # Video Mp4
    8423e75f-3122-4611-afee-1964fdbfecfb: Project # Project
    54418e9f-110f-420c-a76a-a483c9e804e8: 'Iphone Images Mobile' # Iphone Images Mobile
    60529cb1-5e81-4fc9-a15a-073698f15cbb: 'Project Info Section One' # Project Info Section One
    05524087-184e-4d67-b05f-aafdccdcca89: 'Multiple Image Mobile' # Multiple Image Mobile
    47466915-4a43-4556-aafd-f69d5675f48e: 'Single Image Landscape Inset' # Single Image Landscape Inset
    a948a76d-113a-4632-b864-762ff7d15f6d: 'Sam Pittman' # Sam Pittman
    a61356c6-3a08-464d-9afa-eda0180005b5: Home # Home
    b920d452-5bd9-40aa-92fa-84e69daef9c0: 'Awards Category' # Awards Category
    b2906f71-9a84-4426-ad54-c151a5748416: 'Project Image Mobile' # Project Image Mobile
    bb5a6c53-211e-4bfd-ba53-8f4ee55b9ed5: 'Multiple Image Mobile' # Multiple Image Mobile
    bcee0059-a808-47ac-b57e-93d0dd3720fb: 'Single Image' # Single Image
    be3bb3da-e929-4ee1-8690-4243ca4de34c: 'Single Image Mobile' # Single Image Mobile
    c3e6ebfe-019f-471f-9474-26715bf9d326: 'Single Image Landscape Inset Mobile' # Single Image Landscape Inset Mobile
    c18bc7bc-ebf5-49b6-bf40-6e37a47162c6: 'Iphone Images' # Iphone Images
    c767cd90-724c-44f0-b30f-996350098d91: About # About
    cac9403b-b43b-45df-891f-221fbbd360d4: 'Project Type' # Project Type
    ce22344e-204a-45c3-9415-f2e7717f5744: 'Awards List' # Awards List
    d08b26a8-350f-4df5-a004-771b37a0962d: 'Single Image' # Single Image
    d9effeaa-86c2-4b91-a873-bb73981d3993: Contact # Contact
    dc518f4c-dc65-4b41-a20b-bce28b9ed154: 'Single Image Landscape Inset' # Single Image Landscape Inset
    dce78be5-32cc-43d3-9ae2-9ce163274479: Common # Common
    e4fa0978-59c7-448a-9082-e80316245ee5: 'Homepage Project' # Homepage Project
    e6bfa08d-f632-44cc-b594-ff543e957254: 'Hero Image' # Hero Image
    e223bebf-0de5-4d93-a5cc-2eb773f51f8e: 'Project Video' # Project Video
    e1677c95-6b62-406e-b1cd-9366789a84a1: Project # Project
    e121533b-ecc3-46e2-9ee0-868e6cec6f6f: About # About
    ead0d81c-aac3-4a3a-a1bd-191e0e1f2565: 'Main Project Image' # Main Project Image
    ec73bb1a-becb-4f63-b57d-0bb9785ab883: 'Background Colour' # Background Colour
    f0216f6b-7ccc-4684-86f7-5f97be50701e: 'Multiple Image Grid' # Multiple Image Grid
    f1c823d6-fe2e-4e90-87a5-8adeaf85c9d3: 'Awards Year' # Awards Year
    f1e0adf6-7a76-4bd7-aa2d-8d1a63f04c27: 'Multiple Image' # Multiple Image
    f17cdd0f-90a1-448b-b1a2-3f0ebcb5e21e: 'Main Project Image Block' # Main Project Image Block
    f33eb924-bcfe-4787-a561-16563fb3ce7a: 'Single Image Portrait' # Single Image Portrait
    f38b8ca6-b6d6-4379-969d-da980b54c16d: 'Homepage Main Project Type' # Homepage Main Project Type
    f1316259-c5dd-46da-8754-44cf1b7f50c0: 'Iphone Images Grid' # Iphone Images Grid
    fa08560a-67d6-4fc9-a69f-ea4c6667b68a: About # About
    fe0527a7-52ff-443b-be56-4439575db75f: Project # Project
system:
  edition: solo
  live: true
  name: 'Sam Pittman'
  schemaVersion: 3.7.32
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
