defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  a948a76d-113a-4632-b864-762ff7d15f6d: # Sam Pittman
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
